[package]
name = "jaildotconf"
version = "0.1.0"
authors = ["David O'Rourke <david.orourke@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"

[dev-dependencies]
indoc = "1.0"
pretty_assertions = "0.6"
